// SigV4 known-answer test. The expected Authorization headers are GOLDEN VECTORS
// generated by AWS's own reference signer (botocore S3SigV4Auth) under a frozen
// clock — see scripts/uploader/test/README for how they were produced. We assert
// our Node signer reproduces botocore byte-for-byte; if R2 accepts botocore, it
// accepts us. Run: node scripts/uploader/test/sigv4.test.mjs
//
// This is a true known-answer test: the expected values come from the reference
// implementation, NOT from our own code — so it can fail honestly.

import { signRequest } from '../lib/s3.mjs';

const VECTORS = [
  {
    name: 'put_r2_subkey', method: 'PUT', region: 'auto',
    url: 'https://acct123.r2.cloudflarestorage.com/mybucket/AbC123/seg_00000.m4s',
    body: 'hello-shroom-segment',
    amzDate: '20260102T030405Z',
    accessKeyId: 'AKIAIOSFODNN7EXAMPLE',
    secretAccessKey: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
    authorization:
      'AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20260102/auto/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=e913d6b0c8eebcfc69aa7a4ef01d83f9bd4bdae0b4da50203d993479d0bc6da1',
  },
  {
    name: 'put_useast1_empty', method: 'PUT', region: 'us-east-1',
    url: 'https://s3.amazonaws.com/mybucket/AbC123/init.mp4',
    body: '',
    amzDate: '20260102T030405Z',
    accessKeyId: 'AKIAIOSFODNN7EXAMPLE',
    secretAccessKey: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
    authorization:
      'AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20260102/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=c1c6af81e6943e9b10b65cfc631ce437c453f787ca8269a2aa2237acec5e7c1e',
  },
  {
    name: 'head_r2', method: 'HEAD', region: 'auto',
    url: 'https://acct123.r2.cloudflarestorage.com/mybucket/AbC123/seg_00007.m4s',
    body: '',
    amzDate: '20260102T030405Z',
    accessKeyId: 'AKIAIOSFODNN7EXAMPLE',
    secretAccessKey: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
    authorization:
      'AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20260102/auto/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=9d861ba823e1f2753565c7698c13aa6b8b2a439916465808c9600e3445887e2c',
  },
  {
    name: 'put_minio_port', method: 'PUT', region: 'us-east-1',
    url: 'http://127.0.0.1:9000/mybucket/AbC123/stream.m3u8',
    body: '#EXTM3U\n#EXT-X-ENDLIST\n',
    amzDate: '20260102T030405Z',
    accessKeyId: 'AKIAIOSFODNN7EXAMPLE',
    secretAccessKey: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
    authorization:
      'AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20260102/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=a8537d04b8d82460d26b5e5fc5fed7e17639f7ffe9a392ebfea0ca0eca54d532',
  },
];

let failed = 0;
for (const v of VECTORS) {
  const got = signRequest({
    method: v.method, url: v.url, body: v.body, region: v.region,
    accessKeyId: v.accessKeyId, secretAccessKey: v.secretAccessKey, amzDate: v.amzDate,
  });
  if (got.authorization === v.authorization) {
    console.log(`ok   ${v.name}`);
  } else {
    failed++;
    console.error(`FAIL ${v.name}`);
    console.error(`  expected: ${v.authorization}`);
    console.error(`  got:      ${got.authorization}`);
  }
}

console.log(`\n${VECTORS.length - failed}/${VECTORS.length} vectors passed`);
process.exit(failed ? 1 : 0);
